### ISSUE TITLE
init template for cosmos-sdk

### ISSUE THREAD

**Issue by puneet2019** [iqlusioninc/tmkms#125]
in reference to ->
https://github.com/iqlusioninc/tmkms/blob/develop/src/commands/init/templates/schema/cosmos-sdk.toml#L1-L4

Was looking for tmkms signing implementation for cosmos-sdk types, didn't find any example.
it would be great to have an example, also so that we could expand the library.

**Comment by tony-iqlusion** [comment]
`terra.toml` is the one we are using in production now:

https://github.com/iqlusioninc/tmkms/blob/develop/src/commands/init/templates/schema/terra.toml

Note that all of this will change after the Stargate upgrade, since transactions are moving to a Protocol Buffers-based format, so it might be best to wait until that happens.

**Comment by puneet2019** [comment]
yup! thank you for the quick update :+1:

**Comment by RohitAudit** [comment]
@tony-iqlusion 
any timelines for the protobuf updates or anyway to use cosmos message type in schema.

I get below error when trying tx-signer for cosmos-sdk message types
```
error: tmkms fatal error: parse error: invalid character `-` in type name: `cosmos-sdk/MsgVote` for key `tx_signer.acl` at line 40 column 7
```

Below is the schema used for cosmos voting proposal:
```
[[definition]]
type_name = "cosmos-sdk/MsgVote"
fields = [
    { name = "proposal_id",  type = "uint64" },
    { name = "voter", type = "sdk.AccAddress" },
    { name = "option", type = "int32" },
]
```

**Comment by tony-iqlusion** [comment]
We're in the process of migrating to Protobufs and will hopefully have it done this week. I have a local branch I can push up if you're curious, but it isn't yet compiling.

The Protobuf implementation doesn't require TMKMS to have knowledge of the schema.

**Comment by RohitAudit** [comment]
Thanks,
That would be really helpful.
