### ISSUE TITLE
tmkms prometheus endpoint

### ISSUE THREAD

**Issue by franono** [iqlusioninc/tmkms#129]
Would it be possible to have a prometheus endpoint built into tmkms for monitoring. This would allow us to better monitor the KMS module, as at the moment we're monitoring it through its logs.

Some ideas that could be useful:

Counters for:
signed_prevotes
signed_precommits
signed_proposals
timeouts/errors

Other:
Number of validator_connections
hsm_delay time/histogram
chain block heights

Would appreciate your thoughts and possibility of this, thank you!

**Comment by tony-iqlusion** [comment]
Sure, it's a good idea

**Comment by franono** [comment]
Any update on the possibility on including this please? @tony-iqlusion

**Comment by tony-iqlusion** [comment]
There are many other things we are prioritizing at the moment (e.g. Stargate upgrade).

The fastest way to see it added would be to open a PR.

**Comment by tony-iqlusion** [comment]
Closing in favor of #692
