### ISSUE TITLE
tmkms health check

### ISSUE THREAD

**Issue by shiki-tak** [iqlusioninc/tmkms#133]
Is there any way to check if tmkms is starting and working properly?
Is the only way to check the log at present?

Thank you in advance!

**Comment by tony-iqlusion** [comment]
Tendermint KMS doesn't expose any sort of network endpoint (with the exception of the `yubihsm-connector` compatible proxy which is something of a power user option), so there's nothing to poll.

The best way to monitor health is via logging, and making sure it continues to sign blocks successfully. We hope to have a structured logging option available soon.

Someone else recently suggested a Prometheus endpoint #129, which sounds like a reasonable solution to this general problem.

**Comment by shiki-tak** [comment]
Thanks for your comment!
So, since the issue conflicts with #129 , this issue is closed.
