### ISSUE TITLE
Softsign feature

### ISSUE THREAD

**Issue by eugenpro** [iqlusioninc/tmkms#139]
Can somebody provide me a manual for Softsign installation, what should I use as 
as validator addr in this case?
I need to setup node as validator

**Comment by Hapovanille** [comment]
+1, tried the softsign approach with [tm-signer-harness](https://docs.tendermint.com/master/tools/remote-signer-validation.html), but the documentation seems to be outdated. 

Got stuck on the `signing.key` part. I did `tm-signer-harness extract_key -tmhome ~/.tendermint -output ./signing.key` to get a `signing,key`. However when I ran `tmkms start -c tmkms.toml` with the previous `signing.key` provided as `path` field of `[[providers.softsign]]`, I got
```
$ sudo ./tmkms start -c tmkms.toml -v
Sep 28 20:12:00.320 DEBUG abscissa_core::component::registry: registered component: abscissa_core::terminal::component::Terminal (v0.5.2)
Sep 28 20:12:00.320 DEBUG abscissa_core::component::registry: registered component: abscissa_core::trace::component::Tracing (v0.5.2)
Sep 28 20:12:00.320  INFO tmkms::commands::start: tmkms 0.8.0 starting up...
error: error loading configuration: config error: couldn't read key from `/opt/tmkms/signing.key`: stream did not contain valid UTF-8
```
This might be a `tm-signer-harness` issue though, but a softsign manual would be good.

**Comment by tony-iqlusion** [comment]
What format is the key in? The supported formats are Base64-encoded and JSON.

I'm guessing it's the (now deprecated/removed) raw binary format.

**Comment by tony-iqlusion** [comment]
@eugenpro unfortunately the documentation for the softsign backend is undermaintained, as we primarily focus on supporting the `yubihsm` and `ledger` backends.

Use `tmkms softsign keygen /path/to/key` to generate a key, and then adapt this section of the configuration to suit your needs:

https://github.com/iqlusioninc/tmkms/blob/develop/tmkms.toml.example#L56-L59

**Comment by boxi11** [comment]
> What format is the key in? The supported formats are Base64-encoded and JSON.
> 
> I'm guessing it's the (now deprecated/removed) raw binary format.

right it's raw bianry

**Comment by Hapovanille** [comment]
> What format is the key in? The supported formats are Base64-encoded and JSON.
> 
> I'm guessing it's the (now deprecated/removed) raw binary format.

right it was in format of raw binary

**Comment by tony-iqlusion** [comment]
If you Base64 encode it, it should be good

**Comment by tony-iqlusion** [comment]
Closing this out. Please reopen if there's still a problem.
