### ISSUE TITLE
Syncing lag on tendermint 0.33.7

### ISSUE THREAD

**Issue by JoeKash** [iqlusioninc/tmkms#191]
I have an issue syncing a Kava validator.
Not sure if this is tmkms issue or tendermint issue but the problem only manifests when tmkms is being used.

When I configure the node to use tmkms is will fast sync until the latest block but then immediately start lagging behind the chain.
I can't see any errors in the node logs.

If I run tmkms with the verbose flag I can see a lot of request and response for the public key going on (a few dozens a second)
Not sure if this is what's causing the issue or just normal behavior.

If I configure the node to not use a remote signer at all it syncs up an does not lag behind
Any help debugging and solving it will be appreciated

**Comment by tony-iqlusion** [comment]
This sounds like a network connectivity issue between your validator and TMKMS. Tendermint consensus is latency sensitive, so if you have a high-latency link between your validator that will be problematic?

What does e.g. ping say for latency?

**Comment by JoeKash** [comment]
I don't think this is a connectivity issue. 

From the log Ping seem to happen constantly every 100ms - 
`Oct 21 17:26:09.123 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.123 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.221 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.221 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.319 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.319 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.422 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.422 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.520 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.520 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.619 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.619 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.719 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.719 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.818 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.818 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:09.922 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:09.922 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:10.017 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:10.017 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:10.123 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:10.123 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:10.218 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:10.218 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:10.323 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ReplyPing(PingRequest) Oct 21 17:26:10.323 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: Ping(PingResponse) Oct 21 17:26:10.377 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ShowPublicKey(PubKeyRequest ) Oct 21 17:26:10.377 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] acquiring chain registry (for public key) Oct 21 17:26:10.377 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] acquiring read-only shared lock on chain Oct 21 17:26:10.377 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] sending response: PublicKey(PubKeyResponse { pub_key_ed25519: [REDUCTED]}) Oct 21 17:26:10.422 DEBUG tmkms::session: [kava-4@tcp://127.0.0.1:26659] received request: ShowPublicKey(PubKeyRequest )`

Unfortunately I can't run ping command between the two hosts to see the actual network latency.

The thing is it seem like the node will halt for about 2 seconds between each block. and this halt only happen when it's configured to use the remote validator

**Comment by tony-iqlusion** [comment]
Not sure what to tell you then, except that there are other Kava validators using TMKMS who are not experiencing this problem.

**Comment by melekes** [comment]
This can be closed (solved on the Tendermint side; see https://github.com/tendermint/tendermint/issues/5550).
