### ISSUE TITLE
Error with YubiHSM2 and multiple keys

### ISSUE THREAD

**Issue by grizz** [iqlusioninc/tmkms#20]
Running on v0.7.2 -- after adding a second key to the HSM, I got:

`tmkms::client: ... invalid key: expected only one key in keyring`

It is my understanding that the config part `auth = { key = 2 ...` was to define the key index, is that not the case?

Is this just something that hasn't been implemented yet?

**Comment by grizz** [comment]
Oh, actually, key=2 is probably the auth key? Any plans to support more signing keys?

**Comment by tony-iqlusion** [comment]
Presently only one signing key per chain is supported. This is because Tendermint doesn't signal which signing key to use.

While in theory we could otherwise have multiple keys in the keychain, only one can be active at a given time.

Is there a use case you had in mind for multiple keys on a single chain?

**Comment by grizz** [comment]
Any sort of muxing different uses for the HSM comes to mind. In this case, it's an HSM in a dev environment and I was going to bounce between testnet and mainnet.

Is there a better way to do that?

**Comment by tony-iqlusion** [comment]
You can have several keys, but each chain can only have one key. You can have both the testnet and mainnet configured at the same time (so long as they have separate chain IDs)

**Comment by tony-iqlusion** [comment]
As far as I can tell your configuration should be supported. Please reopen if you're still having problems.

**Comment by grizz** [comment]
@tony-iqlusion  -- Yeah, that made sense, thanks and sorry for forgetting to close this.
