### ISSUE TITLE
Tendermint v0.34 support for ledger-validator-app backend

### ISSUE THREAD

**Issue by tony-iqlusion** [iqlusioninc/tmkms#212]
The [ledger-validator-app](https://github.com/tendermint/ledger-validator-app) presently uses Amino encoding. Furthermore, various support code in TMKMS does as well, e.g.:

https://github.com/iqlusioninc/tmkms/blob/develop/src/commands/ledger.rs

The app itself needs to be modified to support the new Protobuf canonicalization/signature format, and then support needs to be added to the TMKMS host-side driver and commands.

**Comment by tony-iqlusion** [comment]
There seems to be a general lack of interest in resolving this issue, and we're unable to locate any validators who are running the Ledger Validator App in production, or anyone interested in funding continued development of the application.

Based on that we have proposed deprecating support for Ledger consensus signing in #292.

**Comment by tony-iqlusion** [comment]
Reopened based on discussion in #292

**Comment by patogit** [comment]
Any more news on this possibility of using Ledger Nano S for validator signing? I'm getting ready for Regen Network mainnet launch, and this would be great! Tagging a few folks from RN: @clevinson @anilCSE @glandua

**Comment by packetstracer** [comment]
I was interested but I guess this is not being developed or in the near future roadmap.

Any news?

**Comment by tony-iqlusion** [comment]
You'd need to find a Ledger developer interested in working on it, and likely pay them, or seek community funds/grants for the development.

**Comment by packetstracer** [comment]
> You'd need to find a Ledger developer interested in working on it, and likely pay them, or seek community funds/grants for the development.

Thanks for the info. I'll stick to the Yubi HSM then.
