### ISSUE TITLE
informational: Non-signed bytes returned in `sign_bytes` function

### ISSUE THREAD

**Issue by tomtau** [iqlusioninc/tmkms#273]
> The implementation of the function TxSigner::sign_bytes simply returns the internal string representation of a SignMsg object. The documentation of the struct clearly states “String representation of a message that describes a particular transaction to be signed by transaction signer.
> It is unclear to a user whether or not if the returned data is signed or if it is to-be signed. This misconception may lead to data being treated signed when it is not, or vice-versa. 
> Recommendation 
> Return signed data or explain properly that the data returned is not actually signed.

**Comment by tony-iqlusion** [comment]
There's going to be a considerable amount of flux in the `TxSigner` code as we migrate from Amino to Protobufs.

You can see some WIP on Protobuf-based signing here: https://docs.rs/cosmos-tx/0.2.0-pre/
