### ISSUE TITLE
Deprecating Ledger support

### ISSUE THREAD

**Issue by tony-iqlusion** [iqlusioninc/tmkms#292]
**HEADS UP: THE LEDGER VALIDATOR APP WILL NOT WORK ON TENDERMINT V0.34 NETWORKS INCLUDING STARGATE**

Note that the Ledger Validator App performs *consensus signing* and is different from the [Ledger Cosmos App](https://github.com/cosmos/ledger-cosmos) which is a wallet application unrelated to TMKMS. 

After some discussion about what to do about #212, we have come to the conclusion that there is little interest in the Ledger Validator App, nor have we been able to find anyone who is actually using it in production.

To update the app for Tendermint v0.34/Stargate compatibility (which uses new message formats and signing algorithms), we would need to find financing to hire a Ledger developer to do the update work. This has not happened and there seems to be a general lack of interest.

Based on that, barring any input to the contrary and financing of the app's ongoing development to retain compatibility, we intend to deprecate Ledger support and remove it from a future TMKMS release.

**Comment by jleni** [comment]
In 2017, Zondax developed this Ledger app for Interchain to provide double-sign protection directly inside the HSM. While not ideal, given that Ledger Nano S devices are consumer devices, at the time it was a very low cost solution accesible to everyone. Several validators started to use it immediately.

We understand that over the years, for different reasons, the validator community may have opted to use alternative approaches. In fact, we were not actively involved in promoting its use. Nevertheles, we hope that over time, the amount of validators using keeping keys in cloud hosts or blind HSMs will decrease.

In any case, if there is any need, we are happy to update both the integration and apps. Moreover, in the next few months we are planning to release something cool that would actually provide a great alternative and we may consider including Tendermint/Stargate support to it. Stay tuned!

**Comment by cwgoes** [comment]
Cryptium presently uses the Ledger validator application in production, sorry for the late response. Thanks for your efforts building & maintaining it. If there is no interest from other validators, we are probably not enough of a reason to continue supporting the app, and we can find alternative solutions.

**Comment by jleni** [comment]
Let me know if you need any help. I think this is something that should be very easy based on what I discussed with Marko. We can talk to Billy and get it done quickly I think.

**Comment by tony-iqlusion** [comment]
Okay, if there's interest in keeping it around we won't deprecate it.

I'll close this and reopen #212 for tracking progress.
