### ISSUE TITLE
Tendermint v0.35 compatibility tracker

### ISSUE THREAD

**Issue by tac0turtle** [iqlusioninc/tmkms#313]
## Summary

Tendermint 0.35 is a couple of months out, but I would like to get some testing in with gRPC. 

- [ ] gRPC Support
 -  gRPC as an alternative to the current custom connection was integrated and tested. tmkms should begin writing support for this as well. I can take a stab at this, I am fairly inexperienced with rust, but it could be a good thing to play around with if no one wants to pick this up.

**Comment by tony-iqlusion** [comment]
Given the current state of TMKMS and various moving parts within the Tendermint/Cosmos Rust ecosystem, it'd probably be best if we tried to integrate it ourselves.

Happy to hop on a call and discuss a testing/integration plan.

**Comment by marbar3778** [comment]
Yea, would love to do that. I can also backport anything to 0.34 line to help with teseting. Will message you on discord about setting up a time.

**Comment by cmwaters** [comment]
Hey, what's the status of the gRPC integration? Tendermint will be removing the legacy socket implementation in v0.36 - https://github.com/tendermint/tendermint/issues/5883

**Comment by tony-iqlusion** [comment]
It's in our roadmap for this quarter

**Comment by tony-iqlusion** [comment]
Tendermint v0.35 was abandoned. See #73 for gRPC support status.
