### ISSUE TITLE
what is the secret key mentioned in the config

### ISSUE THREAD

**Issue by RohitAudit** [iqlusioninc/tmkms#321]
https://github.com/iqlusioninc/tmkms/blob/b06693e13ffcfabb3c0627c584b6af8566cf70bb/tmkms.toml.example#L33

secret_key = "path/to/secret_connection.key"

**Comment by tony-iqlusion** [comment]
This is an identity key used to authenticate the KMS to the validator when using the legacy "Secret Connection" protocol.

It's generated automatically if you use `tmkms init`.

Note that the current plan is to phase out Secret Connection and replace it with gRPC, so this will soon be replaced with an X.509 certificate and associated private key.
