### ISSUE TITLE
Place in a system

### ISSUE THREAD

**Issue by faddat** [iqlusioninc/tmkms#341]
Does this hold the keys, and deliver signed transactions upon request, or does it connect to the peer-to-peer network and act as a validator?

I'm interested in using this so that I can have sentries on akash, and validators in my lair where I have openmptcprouter going and theoretically good connectivity to the planet.

I'm also interested in using this so that I can validate networks like Juno from Raspberry Pi devices even though the smart contracts aren't capable of running on ARM. My personal hunch is that a validator should become a tangible object.

Software like this could potentially allow a single Raspberry Pi to validate multiple networks although I'm not sure if that's desirable from a decentralization / reliability perspective.

I'm going to try it out later today but as I'm sure you guys know trying it out is going to take some time and I figured that I would ask before I do that.

So since this is a complex topic and stuff, let me try to boil it down-- could I use this software like:

**3 sentries in akash**
**1 tmkms instance**

Thanks a lot for any help and pointers, I've come to the realization recently that if one were only signing, the validator could be positively teeny tiny, we could be talking about single core devices and the less complex the validator actually is then the more secure it can be.

*Haven't checked on that single core claim.  Basically collecting hunches here.

**Comment by tony-iqlusion** [comment]
> Does this hold the keys, and deliver signed transactions upon request, or does it connect to the peer-to-peer network and act as a validator?

It only holds keys, with the idea that the validator is kept offline except for communication with sentries.

There are some other options for Tendermint key storage which claim to act as a "validator", but really all these options do is provide equivalent functionality to TMKMS, but suggest you put your "validator" (i.e. the one which signs validated blocks, and proposes blocks) on the edge of the network. This is largely a terminological difference, but the real idea of the sentry architecture is that the Tendermint node which is validating blocks and asking TMKMS to sign PreVotes/PreCommits/Proposals is only seeing P2P traffic which has first passed through a sentry.

> Software like this could potentially allow a single Raspberry Pi to validate multiple networks although I'm not sure if that's desirable from a decentralization / reliability perspective.

The hardware requirements for TMKMS are minimal and this should work if you have a Raspberry Pi running Linux.

**Comment by faddat** [comment]
Hey thank you, I'm getting deeper and deeper into my validator journey and I think that soon in Raspberry Pi of the type that you've described here will enter it.
