### ISSUE TITLE
Signed nil PreCommit

### ISSUE THREAD

**Issue by ljk662** [iqlusioninc/tmkms#38]
I am seeing the following issue with tmkms version `0.6.3` and gaiad version 2.0.8
The signer process will connect to a cosmos validator and logs the following:
```
[cosmoshub-3@tcp://] signed PreCommit:<nil> at h/r/s 1606522/0/2 (104 ms)
[cosmoshub-3@tcp://] signed PreCommit:<nil> at h/r/s 1606523/0/2 (104 ms)
[cosmoshub-3@tcp://] signed PreCommit:<nil> at h/r/s 1606524/0/2 (105 ms)
``

The validator acknowledges a connection with tmkms, starts syncing, and claims to be pushing votes. However, it never signs any blocks and tmkms always shows nil block id.

**Comment by tony-iqlusion** [comment]
A `<nil>` block ID means your validator is voting that it timed out because it did not receive a valid block by the expected block proposer.

**Comment by ljk662** [comment]
@tony-iqlusion It seems this is a tmkms issue, and related to this https://github.com/iqlusioninc/tmkms/issues/24

**Comment by tarcieri** [comment]
#24 is completely unrelated. If you were experiencing it, tmkms would not complete a handshake with Tendermint. The fact it’s signing PreCommits indicates the handshake was completed successfully.

**Comment by ljk662** [comment]
My mistake, you're right. I've also noticed the version of Gaia I'm testing on is not using 0.33+. So as you said, unrelated. My apologies for the false alarm.
