### ISSUE TITLE
Creating backup HSM

### ISSUE THREAD

**Issue by Tomas-Eminger** [iqlusioninc/tmkms#386]
Hi,
I'm trying to create secondary HSM in case of HW failure, to be able to easily replace the faulty one.

As a first step, I initialize a new HSM, save the mnemonic and then generate a consensus key with backup.
In the second step, I initialize secondary HSM using the mnemonic from the first one and then import the backup file from step one. But when I check tmkms yubihsm keys list, on the second I don't get the same pub address.

The Wrap key is the same on both physical devices, so I assume just importing a backup from the first one should work, but it looks like it's not the case.

What am I doing wrong?

**Comment by tony-iqlusion** [comment]
Just as a guess, the configuration may be different from between nodes.

Note that at iqlusion, we run HSMs using the same steps you describe without issues.
