### ISSUE TITLE
 CosmosSDK v0.44.0 (Stargate) compatibility

### ISSUE THREAD

**Issue by Tomas-Eminger** [iqlusioninc/tmkms#409]
Is current version of tmkms compatible with Stargate Cosmos? Terra Columbus-5 is going online in a few hours, I just want to double check, that everything is ready. :)

**Comment by tony-iqlusion** [comment]
I think there's another 34 hours to go before `columbus-5`.

That said, the only notable change is you'll need to set `protocol_version = "v0.34"` in the `[validator]` section.
