### ISSUE TITLE
Yubihsm not working with cosmos-json

### ISSUE THREAD

**Issue by Tomas-Eminger** [iqlusioninc/tmkms#415]
I have managed to test YubiHSM with with agoricdev-5, but when I create new key using:

`tmkms yubihsm keys generate 2 -p agoricvalconspub -b rbf-agoric.enc`

It generates new key which looks like:
```
- 0x0002: [cons] {"@type":"/cosmos.crypto.ed25519.PubKey","key":"XPaVAco/zmax6Qv4/iZYfKVcriB3f1l/d+FW7vSkbvc="}
   label: "agoricvalconspub:2021-10-18T15:12:29Z"
```

But when I create validator with: `{"@type":"/cosmos.crypto.ed25519.PubKey","key":"XPaVAco/zmax6Qv4/iZYfKVcriB3f1l/d+FW7vSkbvc="}`

in tmkms logs I only get this:

`2021-10-18T15:23:24.858371Z ERROR tmkms::client: [agoricdev-5@tcp://10.137.211.10:26658] signing operation failed: signature error`

and from Agoric:

`Oct 18 16:06:18 agoric-testnet ag-chain-cosmos[2917965]: 4:06PM ERR failed signing vote err="exhausted all attempts to sign vote: EOF" height=26289 module=consensus round=0 vote={"block_id":{"hash":"","parts":{"hash":"","total":0}},"height":26289,"round":0,"signature":null,"timestamp":"2021-10-18T16:02:31.707364431Z","type":2,"validator_address":"48E2B3E17D81A4EC7D9C46C74BC23969A0B2EED7","validator_index":5}`

I think there is a still bug, that pubkey shown via tmkms yubihsm keys list is different from the actual one :(

**Comment by Tomas-Eminger** [comment]
I have tried to connect to yubihsm-shell via yubihsm-server feature, but that also doesnt work :(

`tmkms-test@kms:~/kms-testnet$ yubihsm-shell -v 9`
Using default connector URL: http://127.0.0.1:12345`
yubihsm> connect
[LIB - INF 09:34:37.611951] yubihsm.c:4137 (yh_init_connector): Loading http backend
[LIB - INF 09:34:37.619562] yubihsm_curl.c:85 (backend_create): backend_create
[LIB - INF 09:34:37.619608] yubihsm_curl.c:90 (backend_connect): backend_connect
[LIB - INF 09:34:37.619613] yubihsm_curl.c:97 (backend_connect): Trying to connect to http://127.0.0.1:12345/connector/status
[LIB - INF 09:34:37.620289] lib_util.c:139 (parse_status_data): response from connector
[LIB - INF 09:34:37.620309] lib_util.c:140 (parse_status_data): has device: no
[LIB - INF 09:34:37.620312] lib_util.c:141 (parse_status_data): version: 0.0.0
[LIB - INF 09:34:37.620330] lib_util.c:143 (parse_status_data): pid: 0
[LIB - INF 09:34:37.620335] lib_util.c:144 (parse_status_data): address: 
[LIB - INF 09:34:37.620357] lib_util.c:145 (parse_status_data): port: 0
Failed connecting 'http://127.0.0.1:12345': Unable to find a suitable connector
[LIB - INF 09:34:37.620380] yubihsm_curl.c:150 (backend_disconnect): backend_disconnect
[LIB - INF 09:34:37.620420] yubihsm_curl.c:212 (backend_cleanup): backend_cleanup
yubihsm> quit
`tmkms-test@kms:~/kms-testnet$ curl http://127.0.0.1:12345/connector/status`
status
OK
serial
*
version
0.39.0
pid
95182
address
127.0.0.1
port
12345
`tmkms-test@kms:~/kms-testnet$ yubihsm-shell -V`
yubihsm-shell 2.2.0

I think that the signing error is because Cosmos is expecting a different key, because of the mismatched key when creating a validator.

**Comment by tony-iqlusion** [comment]
Well, I ended up bumping a minor version for that release, which unfortunately means TMKMS can't pick up the fix until updated! Unfortunate!

I can try to cut a separate point release with just that change.

**Comment by tony-iqlusion** [comment]
I cut a `signature` v1.3.1 release.

@Tomas-Eminger if you rebuild TMKMS, you should hopefully be able to see the error message now
