### ISSUE TITLE
Add option to export signing key in protobuf json format, when running tmkms generate command

### ISSUE THREAD

**Issue by kobrien** [iqlusioninc/tmkms#466]
in order to register a tendermint validator, the pub key (signing key) needs to be protobuf json encoded. this seems to have recently been enforced with newer versions so previous bech32 formats no longer work, which is the format produced after running `tmkms generate` command.

help text from `gaia tx staking create-validator` command, for --pubkey arg
```
--pubkey string            The validator's Protobuf JSON encoded public key
```

this key format looks like this, which is what you get when you run `gaiad tendermint show-validator` on a validator node.

```
'{"@type":"/cosmos.crypto.ed25519.PubKey","key":"yQxsxXXXXXXYYYYYYZZZZZ"}'
```

however when generating a signing key using tmkms, the format is bech32 like this
```
'cosmosvalconspub1XXXXXXYYYYYYZZZZ' 
```
which produces the following error when trying to register a validator 
```
Error: invalid character 'e' looking for beginning of value
```

**Comment by tony-iqlusion** [comment]
You can set the key format to `cosmos-json` to accomplish this. See #407
