### ISSUE TITLE
Signing silently fails

### ISSUE THREAD

**Issue by zikarad** [iqlusioninc/tmkms#490]
Currently I observe this behaviour of tmkms v0.10.1:
``` 
INFO tmkms::session: [cosmoshub-4@tcp://... signed PreCommit:<nil> at h/r/s SOMEBLOCKHEIGHT/0/2 (0ms)
```
By restarting validator (v6.0.0) it starts correct signing, but after a while  (50-200blocks) the service returns to this bad behaviour again.
What does this means? Is there a solution or workaround? Could this be fixed? An explicit error report would help, too.

Thx!

**Comment by tarcieri** [comment]
`PreCommit:<nil>` indicates your validator node is encountering a consensus timeout.

It’s (likely) not a problem with TMKMS itself, it means your validator is telling TMKMS “please sign this message indicating I timed out waiting on a PreVote quorum”

It’s possible the validator is under too much load to stay in sync.
