### ISSUE TITLE
JSON log output

### ISSUE THREAD

**Issue by freak12techno** [iqlusioninc/tmkms#509]
Hi there.
I'm currently adding ELK for my validator stack and it'd be nice if there was a setting in config that displays all the logs not as colored plain output, but as JSON objects. It'd be way easier to parse it this way. Can this be added?

I guess if not there are ways to parse it properly, but JSON is generally more suitable for machines afaik.

Thanks in advance!

**Comment by Freak12Techno** [comment]
If someone would stumble upon this, this is how I solved it for now using logstash:

```
    if ([journald][process][name] =~ "tmkms") {
        grok {
            match => { "message" => "%{TIMESTAMP_ISO8601:date}%{SPACE}%{LOGLEVEL}%{SPACE}%{NOTSPACE:logger}:%{SPACE}\[%{NOTSPACE:host}\]%{SPACE}%{GREEDYDATA:message}" }
            overwrite => [ "message" ]
        }
    }
```

**Comment by tony-iqlusion** [comment]
It's a good idea, but needs to be added to [Abscissa](https://github.com/iqlusioninc/abscissa)

**Comment by freak12techno** [comment]
@tony-iqlusion should I open another issue on abscissa closing this one then?

**Comment by tony-iqlusion** [comment]
Yep, that'd be great

**Comment by freak12techno** [comment]
Closed this issue in favour of the abscissa one.
