### ISSUE TITLE
Leger setup for tmkms

### ISSUE THREAD

**Issue by YurkoWasHere** [iqlusioninc/tmkms#575]
Question about running ledger_tmkms in 2022 
(lots of outdated documentation out there!)

1) Is the `tendermint` app obsolete and now validator code is just are part of the standard `cosmos app` on ledger live.
2) If not: where do i find the correct app
3) If yes: Currently I am trying to run against the cosmos app and i get a panik

```
$ tmkms start

2022-07-25T22:30:46.941950Z  INFO tmkms::commands::start: tmkms 0.12.0 starting up...
error: error loading configuration: signing operation failed
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Ledger(Apdu("[APDU_CODE_CLA_NOT_SUPPORTED] Class not supported"))
Location: /home/gaia/.cargo/registry/src/github.com-1ecc6299db9ec823/tmkms-0.12.0/src/keyring/providers/ledgertm/signer.rs:40

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.\
```

**Comment by tony-iqlusion** [comment]
We don't use the Ledger app at @iqlusioninc and generally wouldn't recommend it for lack of maintenance.

The app can be found here:

https://github.com/tendermint/ledger-validator-app

It's published for Ledger Live, but I believe hasn't been updated to support newer Ledger devices.

**Comment by YurkoWasHere** [comment]
Thank your @tony-iqlusion for that insight.

From a tmkms perspective, any why this is happening

```
$ tmkms start

2022-07-25T22:30:46.941950Z  INFO tmkms::commands::start: tmkms 0.12.0 starting up...
error: error loading configuration: signing operation failed
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Ledger(Apdu("[APDU_CODE_CLA_NOT_SUPPORTED] Class not supported"))
Location: /home/gaia/.cargo/registry/src/github.com-1ecc6299db9ec823/tmkms-0.12.0/src/keyring/providers/ledgertm/signer.rs:40

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.\
```

**Comment by tony-iqlusion** [comment]
That means the correct application is not running on the Ledger
