### ISSUE TITLE
Unexpected log output showing attempted to double sign

### ISSUE THREAD

**Issue by jennyhys** [iqlusioninc/tmkms#626]
We have a validator node connected to the tmkms server running `0.10.1`, when it is our validator's turn to propose a block the following error would occur and we will be missing block:

```
INFO tmkms::session: signed PreCommit:2A0D4332F9 at h/r/s 4069466/0/2 (0 ms)
INFO tmkms::session: signed PreCommit:66021EF3B0 at h/r/s 4069467/0/2 (0 ms)
INFO tmkms::session: signed Proposal:A56C0AF51D at h/r/s 4069468/0/0 (0 ms)
INFO tmkms::session: signed PreVote:A56C0AF51D at h/r/s 4069468/0/1 (0 ms)
ERROR tmkms::session: attempted double sign PreCommit at h/r/s: 4069468/0/2 (A56C0AF51D != F9D4AB90ED)
```

This seemed to happened to proposing block only but we didn't miss signing other blocks.

**Comment by tony-iqlusion** [comment]
To break down what's happening in the logs, here are the signatures the validator attached to this TMKMS instance is requesting

1. Validator proposed block A56C0AF51D at height 4069468, round 0, step 0
2. Validator signed a PreVote for their proposed block A56C0AF51D at height 4069468, round 0, step 1
3. A conflicting proposal for a different block F9D4AB90ED was made by another validator at height 4069468, round 0, step 2

It's very weird to see two proposals by two different validators at the same height/round, and that's the inherent conflict here.

If this were a simple matter of the proposal for block A56C0AF51D timing out, I would have expected the round to be incremented before another validator makes a proposal.

This almost feels like block A56C0AF51D is being proposed out-of-turn by the validator connected to the TMKMS instance, which would likely indicate some sort of Tendermint bug.

Or if not that, there is something fishy with the proposal which is leading another validator to propose block F9D4AB90ED instead.

It would be good to grep the logs of whatever nodes this particular validator is connected to for the proposed block hash (i.e. A56C0AF51D) and seeing if you can find any error messages about it.

All that said, given these loglines my take is TMKMS's double signing detection is working as intended.

**Comment by Zygimantass** [comment]
I think that internally we came to the same conclusion that this might be a Tendermint bug and that TMKMS actually saved us from a doublesigning event. There was a faulty snapshot (statesynced) that when it was replaced, the issue disappeared.
