### ISSUE TITLE
Add amino schemas for cosmos-sdk

### ISSUE THREAD

**Issue by ewoolsey** [iqlusioninc/tmkms#685]
Specifically referencing this in cosmos-sdk.toml
```
# TODO
#
# If you're interested in this, please open an issue at:
# <https://github.com/iqlusioninc/tmkms>
```
I'm currently working on a project to get ledger support written in rust for the cosmos ledger app. I'm pretty sure I need to use amino encoding in order to get things working. Having this toml is obviously necessary to make that happen.

**Comment by tony-iqlusion** [comment]
I assume this is for Amino JSON specifically?

**Comment by ewoolsey** [comment]
> I assume this is for Amino JSON specifically?

For my use case yes!

**Comment by tony-iqlusion** [comment]
`tx-signer` support was removed in #764
