### ISSUE TITLE
tmkms vs yubihsm2 sdk version dependency

### ISSUE THREAD

**Issue by vchong** [iqlusioninc/tmkms#743]
Is there a way to find out which versions of tmkms support which versions of yubihsm2 sdk (https://developers.yubico.com/YubiHSM2/Releases/)? E.g. if running tmkms v0.12.2, which version of the yubihsm2 sdk should/can be downloaded/run?

**Comment by tony-iqlusion** [comment]
TMKMS doesn't require the YubiHSM SDK

**Comment by tony-iqlusion** [comment]
TMKMS supports directly communicating to the YubiHSM2 via USB.

You're free to use whatever version you'd like if you prefer to use `yubihsm-connector`. Also note that TMKMS has built-in support for presenting a `yubihsm-connector`-compatible service if it talks directly via USB:

https://github.com/iqlusioninc/tmkms/blob/main/tmkms.toml.example#L53
