### ISSUE TITLE
Add support for vote extensions in CometBFT 0.38 or greater

### ISSUE THREAD

**Issue by zmanian** [iqlusioninc/tmkms#835]
Comet BFT adds two new fields to the Vote proto.

During the singing the extension field needs to be used to construct the canonical vote extension messages and then signed with the same signing algorithm as a normal vote message.

Vote extension fields

https://github.com/cometbft/cometbft/blob/main/proto/tendermint/types/types.proto#L138-L141

Message  canonicalization
https://github.com/cometbft/cometbft/blob/main/types/vote.go#L156-L164

Implementation should solve #831

**Comment by tony-iqlusion** [comment]
This was released in v0.13.1 (#845)
