### ISSUE TITLE
Transaction signing from a custom application

### ISSUE THREAD

**Issue by quertc** [iqlusioninc/tmkms#849]
How can I now use softsign/yubihsm for my own apps (e.g. using @cosmjs) after removing tx-signer? I tried using version 0.12.2, which still has tx-signer support, but I got an error after successfully connecting to the validator:

```console
ERROR tmkms::client: [mocha-4@tcp://qwerty@celestia-testnet-example.com:777] protocol error: malformed message packet: failed to decode Protobuf message: PubKeyRequest.chain_id: Message.sum: invalid wire type: Varint (expected LengthDelimited)
```

**Comment by tony-iqlusion** [comment]
The `tx-signer` functionality, as you've discovered, does not support the modern Protobuf transaction encoding. It only supports the legacy Amino encoding, which is why it was removed.

It would be nice to have a new `tx-signer` feature that supports the modern Protobuf encoding, but we have not implemented it yet.

**Comment by quertc** [comment]
Thanks for the info! That would be helpful to see in the future. So at the moment tmkms can only be used for validators, but not for custom apps? Or maybe there is some way to do it.

**Comment by quertc** [comment]
> The `tx-signer` functionality, as you've discovered, does not support the modern Protobuf transaction encoding. It only supports the legacy Amino encoding, which is why it was removed.
> 
> It would be nice to have a new `tx-signer` feature that supports the modern Protobuf encoding, but we have not implemented it yet.

But I also noticed that I have this error even in version 0.13.1. So it's not because of tx-signer. I tried the endpoint of my own validator (celestia/mocha-4) and it worked.

**Comment by tony-iqlusion** [comment]
Oh sorry, misread that message. That's pretty weird and could probably use its own issue.

**Comment by quertc** [comment]
> Oh sorry, misread that message. That's pretty weird and could probably use its own issue.

No problem. But what about the question above? How can I use softsign/yubihsm in nodejs (@cosmjs) apps to sign transactions without tx-signer? Actually the problem in tx-signer is not legacy Amino encoding (since ledger also uses `SIGN_MODE_LEGACY_AMINO_JSON`).

The real problem is weird bugs (e.g. `http://localhost:8080/txns - HTTP error: error trying to connect: Unsupported scheme http`) and schema creation.

**Comment by tony-iqlusion** [comment]
> How can I use softsign/yubihsm in nodejs (@cosmjs) apps to sign transactions without tx-signer? 

We don't currently support any solution for that, sorry. You'll need to ask the CosmJS people.

> Actually the problem in tx-signer is not legacy Amino encoding `SIGN_MODE_LEGACY_AMINO_JSON`.

`tx-signer` used the Amino binary format, not Amino JSON. It is very, very old and has been deprecated for several years. It was replaced by Protobufs around 2019-2020 or so. No Cosmos chain has supported it for many, many years.

**Comment by quertc** [comment]
If anyone is interested. I did remote signing with yubihsm in nodejs app (@cosmjs) using [yubihsm.rs](https://github.com/iqlusioninc/yubihsm.rs) and [neon](https://github.com/neon-bindings/neon) for writing native module. I guess you could also use python lib or yubihsm-shell, but I prefer rust.

@tony-iqlusion thanks for the lib.
