### ISSUE TITLE
Unable to compile for ARM64 from Linux x86_64

### ISSUE THREAD

**Issue by virgilgx** [iqlusioninc/tmkms#889]
I can't compile TMKMS v0.13.1 for the AARM64 achitecture.

Host: Linux 6.8.1-arch1-1  x86_64 (I specify that the following are installed: rustup, aarch64-unknown-linux-gnu, aarch64-linux-gnu-gcc, aarch64-linux-gnu-ld)

The compilation target is therefore : `aarch64-unknown-linux-gnu`
I compile with the following command: `cargo build --release --features=softsign --target=aarch64-unknown-linux-gnu`

Error :  `error adding symbols: file in wrong format`

Here are the full logs : [log.txt](https://github.com/iqlusioninc/tmkms/files/14774537/log.txt)

**Comment by tony-iqlusion** [comment]
It looks like you're cross-compiling, and the host toolchain is trying to link objects for a foreign architecture, which won't work.

You'll need to have an `aarch64` linker installed and tell Cargo to use it in that case. Here is an issue describing how to do that:

https://github.com/rust-lang/rust/issues/28924
